app = 'telegram-bot-delicate-dream-3318'
primary_region = 'fra'

[build]
  image = 'python:3.12-slim'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[vm]
  memory = '1gb'
  cpu_kind = 'shared'