app = "telegram-bot-delicate-dream-3318"
primary_region = "fra"

[experimental]
  auto_rollback = true

[env]

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[vm]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1